json.id recipe.id
json.title recipe.title
json.cook_time recipe.cook_time
json.prep_time recipe.prep_time
json.ingredients recipe.ingredients
json.ratings recipe.ratings
json.cuisine recipe.cuisine
json.category recipe.category
json.author recipe.author
json.image recipe.image
json.complexity recipe.complexity
